// flow-typed signature: 5b6dde8cd8ac2b8cb968c292673e3246
// flow-typed version: <<STUB>>/chess.js_vgithub:jhlywa/chess.js/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chess.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chess.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chess.js/chess' {
  declare module.exports: any;
}

declare module 'chess.js/chess.min' {
  declare module.exports: any;
}

declare module 'chess.js/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chess.js/chess.js' {
  declare module.exports: $Exports<'chess.js/chess'>;
}
declare module 'chess.js/chess.min.js' {
  declare module.exports: $Exports<'chess.js/chess.min'>;
}
declare module 'chess.js/test/tests.js' {
  declare module.exports: $Exports<'chess.js/test/tests'>;
}
